### PR TITLE
Introduce ca reorg

### LINKED ISSUE #50: Generated self-signed certificate does not work in iOS simulator

### PR DESCRIPTION
**Pull request by Blackbaud-BobbyEarl**
We previously asked users to manually trust the CA.  The certificate and key created from that CA were then used in builder.  When we introduced this most recent minor version, we introduced to dynamically generating the certificate and key for all the reasons previously discussed.

This PR basically merges those two techniques.  We now dynamically generate the CA and server certificate and pivot to trust the CA (vs the certificate). This is required in order to fix #50 but also has the added benefit of allowing Firefox users to only have to trust the certificate once vs for each port used (serving multiple SPAs).

I also added a few additional enhancements:

- Dynamically combine commands to run on Windows in to a single batch file in order to to have a single elevated credentials prompt (Mac/Linux do this automatically when running multiple commands with `sudo`).
- Catch users running `skyux install certs` instead of `skyux certs install`.  This was based on some third-party feedback as well as me accidentally typing it once.
- Better logging when a subtask fails.  Previously, we'd say it failed but then say the entire operation was successful.
- Upgraded devDependencies to fix a bug, which resulted in exposing a few leaky mocks.

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Introduced your feedback @Blackbaud-TerryHelems.

**Comment by Blackbaud-BobbyEarl** [comment]
Incorporated feedback from @Blackbaud-TerryHelems.

**Comment by Blackbaud-BobbyEarl** [comment]
> Works great, locally (except for Firefox, of course). LGTM!

Good point about Firefox.  I'm working a docs PR now, but Firefox users will continue to have two options (we currently only document one as I just found out about the other).

1. Manually import and trust the CA.
2. Set `security.enterprise_roots.enabled` which basically tells Firefox to use the machine's trusted store.

**Comment by Blackbaud-TerryHelems** [comment]
I noticed on Windows that the temp batch file remains behind if I say `No` to the `UAC` prompt. When selecting `Yes`, this file gets cleaned up.

**Comment by Blackbaud-BobbyEarl** [comment]
Docs PR previously mentioned: https://github.com/blackbaud/skyux2-docs/pull/774

**Pull request merged**
